---
title: "benchmark_amppred"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
tg_amppred <- read_faa("tmpdata/amppred/amp_amppred_fasta")

tg_amppred$Label <- "Tg"

bg_amppred <- read_faa("tmpdata/amppred/nonamps_amppred.fasta")

bg_amppred <- bg_amppred[!duplicated(bg_amppred$seq.aa),]

bg_amppred$Label <- "Bg"

bg_tg_amppred <- rbind(bg_amppred, tg_amppred)

bg_tg_amppred <- bg_tg_amppred[nchar(bg_tg_amppred$seq.aa) >=20,]


features_amppred <- calculate_features(bg_tg_amppred)

features_amppred$Label <- bg_tg_amppred$Label

features_amppred[["Label"]] <- factor(features_amppred[["Label"]])


```



```{r}

trainamppredIndex <-createDataPartition(y=features_amppred$Label, p=.7, list = FALSE)
featuresamppredTrain <-features_amppred[trainamppredIndex,]
featuresamppredTest <-features_amppred[-trainamppredIndex,]


trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3, classProbs = TRUE)

svm_amppredtgbg <- train(Label~., data = featuresamppredTrain[,-c(1,27:45)], method="svmRadial", trControl = trctrl, preProcess = c("center", "scale"),
                    tuneLength = 10)


#train amppred model with all their data
svm_amppred_all <- train(Label~., data = features_amppred[,-c(1,27:45)], method="svmRadial", trControl = trctrl, preProcess = c("center", "scale"),
                    tuneLength = 10)




```

```{r}
test_amppred <- predict(svm_amppredtgbg, newdata = featuresamppredTest)

confusionMatrix(test_amppred, featuresamppredTest$Label)

library(mltools)

mcc(TP = 687, FP = 34, TN = 221, FN = 59)

library(pROC)

test_pred_prob <- predict(svm_amppredtgbg, featuresamppredTest, type = "prob")
roc_out <- roc(featuresamppredTest$Label, test_pred_prob$Tg)

```

```{r}

featuresTest_1000 <- readRDS("tmpdata/1000_test_features.rds")

#test with 1000 sp proteins
test_amppred1000 <- predict(svm_amppred_all, newdata = featuresTest_1000)

confusionMatrix(test_amppred1000, featuresTest_1000$Label)

library(mltools)

mcc(TP = 476, FP = 25, TN = 20, FN = 479)

library(pROC)

test_pred_prob <- predict(svm_amppred_all, featuresTest_1000, type = "prob")
roc_out <- roc(featuresTest_1000$Label, test_pred_prob$Tg)
```


```{r}
#results from iamppred website from 1000 test proteins
amppred_1000 <- read.csv("tmpdata/amppred/amppred_1000.csv") 

amppred_1000 <- amppred_1000[,-1]

amppred_1000$Label <- NA

#amppred_1000$Label[amppred_1000$antibacterial>=.50|amppred_1000$antiviral>=.50|amppred_1000$antifungal>=.50] = "Tg"

amppred_1000$Label[amppred_1000$antibacterial>=.50|amppred_1000$antifungal>=.50] = "Tg"

amppred_1000$Label[amppred_1000$antibacterial>=.50] = "Tg"

amppred_1000$Label[is.na(amppred_1000$Label)] = "Bg"

amppred_1000$Label <- as.factor(amppred_1000$Label)

length(grep("Bg", amppred_1000$Label)) #67 $127 antibac only

length(grep("Tg", amppred_1000$Label)) #933 #873 antibac only

```



```{r}
#predicted against reference (true results)
library(caret)
confusionMatrix(amppred_1000$Label, featuresTest_1000$Label)

library(mltools)
mcc(TP = 417, FP = 84, TN = 43, FN = 456)


library(pROC)


roc(featuresTest_1000$Label, amppred_1000$antibacterial)


```


