# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_paac <- function(seq, H, lambda, w) {
    .Call(`_ampir_rcpp_paac`, seq, H, lambda, w)
}

