---
title: "random_aa"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
random_aa <- function(x) {
  
  #x is the length of the sequence
  aa <- c('A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I','L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y','V')
  aa_r <- sample(aa, x, replace = TRUE)
  aa_r <- paste(aa_r, collapse ="") 
  
  aa_r
}

#n is number of sequences
random_aas <- function(n, min_length = 10, max_length = 2000){
  lengths <- round(runif(n,min=min_length,max=max_length))
  sapply(lengths, random_aa)
}

```

```{r}

#gives 1 sequence 70aa long
random_aa(70)

#gives 10 sequences at lengths between 10 and 2000
random_aas(10)

#get # sequences at ## length.
replicate(7, random_aa(60))

```

```{r}
randoms <- random_aas(100)
randoms <- as.data.frame(randoms)
names(randoms)[1] <- "seq.aa"

randoms2 <- random_aas(100)
randoms2 <- as.data.frame(randoms2)
names(randoms2)[1] <- "seq.aa"

randoms3 <- random_aas(100)
randoms3 <- as.data.frame(randoms3)
names(randoms3)[1] <- "seq.aa"

```


