---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library(magrittr) (magrittr included with tidyverse?)
library(Peptides)
library(tidyverse)
library(protr) 

source("calc_amphiphilicity.R")
source("calc_composition.R")
source("calc_hydrophobicity.R")
source("calc_length.R")
source("calc_mw.R")
source("calc_net_charge.R")
source("calc_pI.R")
source("read_faa.R")

source("calculate_features.R")

```

```{r}
little_test <- read_faa("little_test.fasta")
```


```{r}


calculate_features(little_test$seq.aa)

yay <- calculate_features(little_test$seq.aa)



```


```{r}
pseudo_test <- calc_pseudo_comp(little_test$sequence[5])
```


```{r_stuffing_around}
Sequence <- little_test$seq.aa


anything <- function(Sequence) {
  little_test %>% filter(grepl('^[ARNDCEQGHILKMFPSTWYV]+$', Sequence))
  
  return(little_test)
}


#little_test %>% filter(grepl('^[ARNDCEQGHILKMFPSTWYV]+$', Sequence))
for f in sequence_files {
  # read file into dataframe
  df <- readfile(f)
  # process datframe through our function
  result <- aynything(df.sequence)
  # do something with this result
  savefile(df) # for example save the result
}
  

x <- anything(little_test$seq.aa)


little_test %>% filter(grepl('^[ARNDCEQGHILKMFPSTWYV]+$', seq.aa))



#colnames(little_test)[2] <- "sequence"




remove_nonstandard_aa(little_test$seq.aa)

# remove_nonstandard_aa <- function(seq) {
#   df %>% filter(grepl('^[ARNDCEQGHILKMFPSTWYV]+$', seq))
# }

```



